version: '3.3'

services:
  db1:
    image: mysql:latest
    # restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'venkat'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'venkat'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      innodb_fast_shutdown: 1
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db1:/var/lib/mysql
    hostname: www2
    container_name: www2
# Names our volume
volumes:
  my-db1:

networks:
  default:
    name: health-network
    external: true
